### ISSUE TITLE
Error using Platypus with libgsl-dev

### ISSUE THREAD

**Issue by hakonhagland** [Perl5-FFI/FFI-Platypus#176]
I am trying to use some math functions from the GSL math library. See [this link](https://www.gnu.org/software/gsl/doc/html/roots.html) for a full example. Currently my perl FFI script crashes, so I have reduced it to a minimal example.

Consider this C program:
```c
#include <gsl/gsl_roots.h>
int main (void)
{
    gsl_root_fdfsolver *s = gsl_root_fdfsolver_alloc ( gsl_root_fdfsolver_newton );
    return 0;
}
```
I compile it with (you can install the gsl library on Ubuntu from package `libgsl-dev`)
```
gcc  -o solve solve.c -lgsl -lgslcblas
```
and I can run it without any crashes:
```
$ ./solve
$ # no output from above command
```
Then, here is the FFI perl script:
```perl
#! /usr/bin/env perl
use strict;
use warnings;
use FFI::Platypus;
use FFI::CheckLib;
my $ffi = FFI::Platypus->new();
$ffi->lib( find_lib_or_exit( lib => 'gsl' ) );
$ffi->type('opaque'       => 'gsl_root_fdfsolver_type_ptr');
$ffi->attach(
    'gsl_root_fdfsolver_alloc',
    [ 'gsl_root_fdfsolver_type_ptr' ] => 'opaque'
);
my $solver_type = $ffi->find_symbol('gsl_root_fdfsolver_newton');
my $solver = gsl_root_fdfsolver_alloc( $solver_type );
```
This crashes with error:
```
$ p.pl
gsl: fdfsolver.c:45: ERROR: failed to allocate space for root solver state
Default GSL error handler invoked.
Aborted (core dumped)
```
You can find the C-types in [fdfsolver.c](http://git.savannah.gnu.org/cgit/gsl.git/tree/roots/fdfsolver.c) and in [newton.c](http://git.savannah.gnu.org/cgit/gsl.git/tree/roots/newton.c).

I have tried to debug it, and it seems that the wrong argument is passed to `gsl_root_fdfsolver_alloc()`.. Any idea what might be the problem?

**Comment by hakonhagland** [comment]
Sorry forgot to add the title :)

**Comment by hakonhagland** [comment]
Seems like there is no way to change the title, see https://github.com/GitHawkApp/GitHawk/issues/1631 

Should I post a new issue (then this can be deleted afterwards I guess)?

**Comment by hakonhagland** [comment]
As far as I can see the call `ptr = dlsym(handle, symbol)` at line #62 in `xs/DL.xs`  returns the wrong address for the symbol `gsl_root_fdfsolver_newton`. I am not sure where the call to `dlsym()` goes. Is it in `libc` ?

**Comment by plicease** [comment]
`dlsym` comes from `libdl` (header file is `dlfcn.h`), which should already be linked into perl because it uses it for XS.

I wonder if the problem has something to do with missing `libgslcblas` in the FFI version.  Normally though if that is the problem it will give you an error when you try to `attach`/`find_symbol`, which is not the case here.  Though I don't know enough about the gsl internals to say for sure.  Sometimes you can work around this by pre-loading the dependency like this:

```perl
{
  use FFI::Platypus::DL qw( dlopen dlerror RTLD_NOW RTLD_GLOBAL );
  my($gslcblas) = find_lib_or_die( lib => 'gslcblas');
  warn "gslcblas = $gslcblas";
  my $h = dlopen($gslcblas, RTLD_NOW | RTLD_GLOBAL) || die "error loading $gslcblas " . dlerror();
}
```

but that didn't seem to help in this case.  (related #127 )

**Comment by hakonhagland** [comment]
> I wonder if the problem has something to do with missing libgslcblas in the FFI version

I created [a minimal version of `libgsl.so`](https://github.com/hakonhagland/gsl-fdfsolver-debug) and it shows that  it is not related to `libgslcblas` missing. The problem is still present in this minimal example. Somehow the address obtained by `my $solver_type = $ffi->find_symbol('gsl_root_fdfsolver_newton')` is not correct.

**Comment by plicease** [comment]
Ah I went down a rabbit hole for a second but I think I see what is going on now.  Thanks for the simplified example, that made it much easier to debug.  `gsl_root_fdfsolver_newton` is expecting not `gsl_root_fdfsolver_newton`, but the thing that it is pointing to.

```diff
diff --git a/p.pl b/p.pl
index 4ce4ac6..5dcedc9 100755
--- a/p.pl
+++ b/p.pl
@@ -11,8 +11,8 @@ my $function = $ffi->function(
     'gsl_root_fdfsolver_alloc',
     [ 'gsl_root_fdfsolver_type_ptr' ] => 'opaque'
 );
-my $solver_type = $ffi->find_symbol('gsl_root_fdfsolver_newton');
-my $solver = $function->call( $solver_type );
+my $solver_type = $ffi->cast('opaque' => 'opaque*', $ffi->find_symbol('gsl_root_fdfsolver_newton'));
+my $solver = $function->call( $$solver_type );
 ```

```
% perl p.pl 
The input parameter 'T' should be equal to the global symbol 'gsl_root_fdfsolver_newton'... checking:
  T = 0x1084b8018
  gsl_root_fdfsolver_newton = 0x1084b8018
  --> ok!
```

When I use the cast on the real libgsl it works correctly.

**Comment by hakonhagland** [comment]
Great! It works!! Though, I must admit it is still a little bit confusing when to use `opaque` and when to use `opaque*`

**Comment by plicease** [comment]
`opaque` is a pointer, but it is better to think of it as a handle for something that the library you are calling understands the structure of, but that you don't have to care about that structure from Perl space.   `opaque*` is a pointer to that handle.  Normally when you need to use an `opaque*` is when a function returns an `opaque` type as an argument rather than a return value (since `opaque` is passed by value).

Another way to think about it from a C perspective is `opaque` is a `void*` and `opaque*` is a `void**`.
