### ISSUE TITLE
What type to use for an enum?

### ISSUE THREAD

**Issue by rabbiveesh** [Perl5-FFI/FFI-Platypus#181]
My work on libpostal is coming along nicely. I have another question now: I don't see anything in the docs about what type I should declare when the type is a C `enum`. I saw there was a recent pull request that mentioned `enum`s being non-straightforward. But it also mentioned a lack of documentation.

In any case, here's the enum I want to copy:
```C
typedef enum {
    LIBPOSTAL_NULL_DUPLICATE_STATUS = -1,
    LIBPOSTAL_NON_DUPLICATE = 0,
    LIBPOSTAL_POSSIBLE_DUPLICATE_NEEDS_REVIEW = 3,
    LIBPOSTAL_LIKELY_DUPLICATE = 6,
    LIBPOSTAL_EXACT_DUPLICATE = 9,
} libpostal_duplicate_status_t;
```

I noticed that 'enum' is a reserved keyword in V1, but I don't know how to use it.

**Comment by plicease** [comment]
`enum` and `senum` are the integer types used for enums and signed enumes respectively.  (a signed enum is just an enum that has negative values, it's not a separate type in C, but the compiler may treat them differently).  These types are at the discretion of the compiler/ABI so Platypus probes for them so that you do not have to.

The values don't exist in the .so or .dll file which is the tricky part.  (From an FFI perspective they are more or less the same as `#define` constants).  So there are two choices,

 1. define constants using the `constant` pragma.  This is usually best if there are only a few possible values and they don't change from lib version to version or from os to os:

https://metacpan.org/pod/FFI::Platypus#How-do-I-get-constants-defined-as-macros-in-C-header-files

 2. You can bundle some C code with your dist that defines the constants in Perl space from C. I think this is primarily useful if the constants change from version-to-version or platform to platform:

https://metacpan.org/pod/FFI::Platypus::Constant

It can be handy to define a macro so you don't have to repeat yourself, like so:

https://github.com/genio/p5-UV-FFI/blob/master/ffi/Constants.c#L73-L74

The bundle interface DOES require that you have a compiler at build time, but because the .so or .dll file is installed along with your .pm files it can be deployed where you do not have a compiler (in this sense it is very similar to XS).

Documentation should be updated

 * The FAQ for constants should be updated to mention enum types.
 * The FAQ for constants should link to `FFI::Platypus::Constant`.  This can wait until the interface is non-experimental.

**Comment by plicease** [comment]
Added a note about documentation improvements TODOs to #184
